# Generated by Django 4.2.5 on 2023-10-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='avialability',
            field=models.BooleanField(default=False),
        ),
    ]
